server:
  port: 8081

spring:
  application:
    name: cloudE-ucenter-provider
  cloud:
    config:
      uri: http://localhost:8888

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.cloudE.mapper

eureka:
  instance:
    prefer-ip-address: true
